export const queryKeys = {
  lookups: ["lookups"] as const,
  dashboard: (year?: number, month?: number) =>
    ["dashboard", year ?? "current", month ?? "current"] as const,
  dashboardRevenue: (start?: string, end?: string) => ["dashboard", "revenue", start, end] as const,
  dashboardExpenses: (start?: string, end?: string) => ["dashboard", "expenses", start, end] as const,
  vehicles: (page: number) => ["vehicles", page] as const,
  vehicle: (id: number) => ["vehicle", id] as const,
  vehicleMaintenances: (id: number, page: number) => ["vehicles", id, "maintenances", page] as const,
  vehicleExpenses: (id: number, page: number) => ["vehicles", id, "expenses", page] as const,
  locations: (page: number) => ["locations", page] as const,
  blogPosts: (page: number) => ["blog-posts", page] as const,
  customers: (page: number) => ["customers", page] as const,
  customer: (id: number) => ["customer", id] as const,
  vehicleBrands: (page: number) => ["vehicle-brands", page] as const,
  vehicleCategories: (page: number) => ["vehicle-categories", page] as const,
  reservations: (page: number) => ["reservations", page] as const,
  reservation: (id: number) => ["reservation", id] as const,
  reservationCalendar: (start?: string, end?: string) => ["reservations", "calendar", start, end] as const,
  paymentSummary: (reservationId: number) => ["payments", "summary", reservationId] as const,
  contract: (reservationId: number) => ["contracts", reservationId] as const,
  payments: (page: number) => ["payments", page] as const,
  maintenances: (page: number) => ["maintenances", page] as const,
  upcomingMaintenances: (page: number) => ["maintenances", "upcoming", page] as const,
  expenses: (page: number) => ["expenses", page] as const,
  expenseSummary: (year?: number, month?: number) => ["expenses", "summary", year, month] as const,
  alerts: (page: number) => ["alerts", page] as const,
  pendingAlerts: (page: number) => ["alerts", "pending", page] as const,
  users: (page: number) => ["users", page] as const,
  user: (id: number) => ["user", id] as const,
  roles: ["roles"] as const,
  permissions: ["permissions"] as const,
};
